version: "3"
services:
  wordpress:
    image: wordpress:${WORDPRESS_VERSION}
    container_name: wordpress
    ports:
      - "${WORDPRESS_PORT}:80"
    environment:
      WORDPRESS_DB_HOST: "mysql"
      WORDPRESS_DB_USER: "root"
      WORDPRESS_DB_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      WORDPRESS_DB_NAME: "${MYSQL_DATABASE}"
      WORDPRESS_TABLE_PREFIX: "wp_"
      TZ: "${TZ}"
    volumes:
      - "${WORDPRESS_DATA_DIR}:/var/www/html"
    restart: always
    networks:
      - default

  mysql:
# if you are using arm64 you should change image to mysql/mysql-server:< version >= 8.0 >
#    image: mysql:${MYSQL_VERSION}
    image: mysql/mysql-server:${MYSQL_VERSION}
    container_name: mysql
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - "${MYSQL_DATA_DIR}:/var/lib/mysql/:rw"
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      TZ: "${TZ}"
    restart: always
    networks:
      - default
